// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebApi.Data;

namespace WebApi.Migrations
{
    [DbContext(typeof(MainDbContext))]
    [Migration("20210413193731_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn);

            modelBuilder.Entity("WebApi.Models.DayMenu", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn);

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<long>("RecipeListId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("RecipeListId");

                    b.ToTable("DayMenu");
                });

            modelBuilder.Entity("WebApi.Models.Recipe", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn);

                    b.Property<int>("Carbohydrates")
                        .HasColumnType("integer");

                    b.Property<int>("Colories")
                        .HasColumnType("integer");

                    b.Property<int>("Greases")
                        .HasColumnType("integer");

                    b.Property<bool>("HaveMeat")
                        .HasColumnType("boolean");

                    b.Property<byte[]>("Image")
                        .HasColumnType("bytea");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("Proteins")
                        .HasColumnType("integer");

                    b.Property<long?>("RecipeListId")
                        .HasColumnType("bigint");

                    b.Property<int>("Weight")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RecipeListId");

                    b.ToTable("Recipe");
                });

            modelBuilder.Entity("WebApi.Models.RecipeList", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn);

                    b.HasKey("Id");

                    b.ToTable("RecipeList");
                });

            modelBuilder.Entity("WebApi.Models.DayMenu", b =>
                {
                    b.HasOne("WebApi.Models.RecipeList", "RecipeList")
                        .WithMany("DayMenus")
                        .HasForeignKey("RecipeListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RecipeList");
                });

            modelBuilder.Entity("WebApi.Models.Recipe", b =>
                {
                    b.HasOne("WebApi.Models.RecipeList", "RecipeList")
                        .WithMany("Recipes")
                        .HasForeignKey("RecipeListId");

                    b.Navigation("RecipeList");
                });

            modelBuilder.Entity("WebApi.Models.RecipeList", b =>
                {
                    b.Navigation("DayMenus");

                    b.Navigation("Recipes");
                });
#pragma warning restore 612, 618
        }
    }
}
