// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebApi.Data;

namespace WebApi.Migrations
{
    [DbContext(typeof(MainDbContext))]
    [Migration("20210413201753_update1")]
    partial class update1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn);

            modelBuilder.Entity("WebApi.Models.DayMenu", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn);

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DayMenu");
                });

            modelBuilder.Entity("WebApi.Models.Recipe", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn);

                    b.Property<int>("Carbohydrates")
                        .HasColumnType("integer");

                    b.Property<int>("Colories")
                        .HasColumnType("integer");

                    b.Property<int>("Greases")
                        .HasColumnType("integer");

                    b.Property<bool>("HaveMeat")
                        .HasColumnType("boolean");

                    b.Property<byte[]>("Image")
                        .HasColumnType("bytea");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("Proteins")
                        .HasColumnType("integer");

                    b.Property<int>("Weight")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Recipe");
                });

            modelBuilder.Entity("WebApi.Models.RecipeList", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn);

                    b.Property<long?>("DayMenuId")
                        .HasColumnType("bigint");

                    b.Property<long?>("RecipeId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("DayMenuId");

                    b.HasIndex("RecipeId");

                    b.ToTable("RecipeList");
                });

            modelBuilder.Entity("WebApi.Models.RecipeList", b =>
                {
                    b.HasOne("WebApi.Models.DayMenu", "DayMenu")
                        .WithMany("RecipeList")
                        .HasForeignKey("DayMenuId");

                    b.HasOne("WebApi.Models.Recipe", "Recipe")
                        .WithMany("RecipeList")
                        .HasForeignKey("RecipeId");

                    b.Navigation("DayMenu");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("WebApi.Models.DayMenu", b =>
                {
                    b.Navigation("RecipeList");
                });

            modelBuilder.Entity("WebApi.Models.Recipe", b =>
                {
                    b.Navigation("RecipeList");
                });
#pragma warning restore 612, 618
        }
    }
}
